# Generated by Django 6.1.1 on 2026-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('degree_level', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=200)),
                ('funding_type', models.CharField(choices=[('fully_funded', 'Fully Funded'), ('partially_funded', 'Partially Funded'), ('tuition_only', 'Tuition Only'), ('stipend', 'Stipend Based')], max_length=30)),
                ('funding_amount', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
