# Generated by Django 6.1.1 on 2026-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_add_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='application_url',
            field=models.URLField(blank=True, help_text='URL where students can apply', max_length=500),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=True),
        ),
    ]
